---
- hosts: all
  sudo: yes
  tasks:
      - name: create storage filesystem
        filesystem: fstype=ext4 dev=/dev/xvdb
      - name: mount storage filesystem
        mount: name=/srv/streams src=/dev/xvdb fstype=ext4 state=mounted opts=defaults,noatime
      - name: chown storage mount
        file: path=/srv/streams owner=wowza group=wowza recurse=yes
      - name: wowza app configuration directory
        file: path={{ wowza_home }}/conf/live owner=wowza group=wowza mode=0755 state=directory
      - name: wowza app configuration
        copy:
            src: conf/Application.xml
            dest: "{{ wowza_home }}/conf/live/Application.xml"
            owner: wowza
            group: wowza
            mode: 0644
            validate: "xmllint %s"
        notify:
            - restart wowza
      - name: transcoder configuration
        copy:
            src: "{{ item }}"
            dest: "{{ wowza_home }}/transcoder/templates/"
            owner: wowza
            group: wowza
            mode: 0644
            validate: "xmllint %s"
        with_items:
            - conf/transcoder/audioonly.xml
            - conf/transcoder/transcode-h265-divx.xml
            - conf/transcoder/transcode.xml
            - conf/transcoder/transrate.xml
        notify:
            - restart wowza
  handlers:
      - name: restart wowza
        service: name=WowzaStreamingEngine state=restarted
